### ISSUE TITLE
Slack link is dead

### ISSUE THREAD

**Issue by carsonharmon** [twosixlabs/acsploit#1]
Hey TwoSix :) 

Your slack link is dead! Any chance y'all wanna throw up a new one?

**Comment by adamj26** [comment]
The link has been updated with 4c636d1eccf3d8d3dfc84f6bf1e17026d363dde8

Apologies for our delay in handling this

**Comment by weddige** [comment]
The link is dead again.

**Comment by adamj26** [comment]
Thanks for letting us know! We're looking into creating a new one.

**Comment by Cyborg369** [comment]
The link is dead again.

**Comment by adamj26** [comment]
Yes; we are currently working on creating a new long-term invite link and will update the README and this issue once it is available.

In the meantime, if you would like to join the Slack, please use the below link, which will be valid through 2021-04-07:
https://join.slack.com/t/acsploit/shared_invite/zt-7v2fwif6-8ppJyUkirqqHxdYq744PWQ
